# Generated by Django 3.1.13 on 2022-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220522_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='isCorrect',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='textChoice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='textQuestion',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=33, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.BigIntegerField(default=0),
        ),
    ]
